// SPDX-License-Identifier: AGPL-3.0-or-later
// `B976`. After every dpkg run, a program installed with a capability this
// machine never grants (`ping`'s cap_net_raw: the container drops NET_RAW,
// `P20-06`) has it taken out, so it starts instead of being refused at exec.
// What and why: workstation/netraw.py. Installed by the container image only.
DPkg::Post-Invoke { "cd /opt/pantheon-workstation && python3 -B -m workstation.netraw || true"; };
