#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Vendor Swagger UI into static/lib/swagger-ui/ from a checksum-verified artifact.

`B212`. FastAPI builds `/docs` itself and its HTML names `cdn.jsdelivr.net` for
the stylesheet and the bundle, plus `fastapi.tiangolo.com` for a favicon. The
CSP refused all three, so no request left -- but a served page that *names*
three hosts nobody chose is what `Law 16` is about, and it sat in the one part
of the served surface `test_no_cdn_anywhere_in_served_frontend` could not see,
because that test scanned `static/**` and this document is generated by a
library at request time.

This is the same shape as `scripts/fetch-pyodide.py` and deliberately not a
loop of `curl`s at a CDN. It downloads **one** artifact -- the npm registry
tarball -- checks it against the SHA-512 the registry publishes as
`dist.integrity` *before* opening it, and then checks every extracted file
against a hash pinned in this file. Two independent statements have to agree
before anything is written:

    registry says      : the tarball hashes to <dist.integrity>
    this file says     : each extracted file hashes to PINNED[name]

A CDN GET can only ever tell you what that CDN served you. (The pinned hashes
below were cross-checked against what cdn.jsdelivr.net serves at
`swagger-ui-dist@5`: byte-identical. Two origins, one set of hashes.)

    python3 scripts/fetch-swagger-ui.py          # fetch, verify, write
    python3 scripts/fetch-swagger-ui.py --check  # verify what is on disk
    python3 scripts/fetch-swagger-ui.py --version 5.33.0

WHY TWO FILES AND NOT THE WHOLE DIST. The published package unpacks to 11.7 MB
-- ES bundles, a standalone preset, source maps, an OAuth redirect page we
already serve ourselves. FastAPI's docs HTML loads exactly two of them, so
those two are what ships. `swagger-ui-standalone-preset.js` is deliberately NOT
among them: the generated page references `SwaggerUIBundle.SwaggerUIStandalonePreset`,
which is undefined without it, and that is true of upstream FastAPI's own
`/docs` against jsDelivr as well. Vendoring does not narrow what worked; it
makes what already happened happen locally.

The stylesheet's every `url()` is a `data:` URI -- no fonts, no sprites, no
second request -- which is why `/docs` needs nothing from `font-src` and is
answerable in full by `default-src 'self'` plus `img-src data:`.
"""
import argparse
import base64
import hashlib
import io
import json
import pathlib
import sys
import tarfile
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEST = ROOT / "static" / "lib" / "swagger-ui"
LICENSES = ROOT / "licenses"
REGISTRY = "https://registry.npmjs.org/swagger-ui-dist"

VERSION = "5.32.15"

# SHA-256 of each vendored file, recorded when it was first vendored
# (2026-09-16). `swagger-ui-bundle.js.LICENSE.txt` is webpack's extracted
# notice for the MIT-licensed packages inside the bundle; it lands in
# `licenses/`, next to the same sidecar html2pdf ships (`P0-21b`).
PINNED = {
    "swagger-ui.css":
        "d7f39f764aa18c7b47dd05b9af5613e373e4ac0f3557c2693d52d0abc2464d76",
    "swagger-ui-bundle.js":
        "a7e344f2770b2f07527ce828e0951626983b8f2dcdb7a826689c0232023f995b",
}

# Paperwork that travels with the bytes, written to licenses/ rather than into
# the vendored root: `check-licences.py` rule 1 fails on an undeclared file
# under `static/lib/`, and rule 4 fails on an orphan text in `licenses/` — so
# each of these is claimed by an INVENTORY entry there. They are not in PINNED
# because they are not served: nothing on `/docs` requests a licence text, and
# a hash here would be a second place to update for a file whose contents the
# checker already reads.
LICENCE_FILES = {
    "LICENSE": "SwaggerUI-Apache-2.0.txt",
    "NOTICE": "SwaggerUI-NOTICE.txt",
    "swagger-ui-bundle.js.LICENSE.txt": "swagger-ui-bundle.js.LICENSE.txt",
}


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def check_on_disk(pinned=PINNED) -> int:
    """Verify what is already vendored. No network, no writes."""
    bad = []
    for name, want in sorted(pinned.items()):
        f = DEST / name
        if not f.is_file():
            bad.append(f"MISSING  {name}")
            continue
        got = sha256(f.read_bytes())
        if got != want:
            bad.append(f"MISMATCH {name}\n         want {want}\n         got  {got}")
    manifest = DEST / "MANIFEST.json"
    if not manifest.is_file():
        bad.append("MISSING  MANIFEST.json")
    else:
        recorded = json.loads(manifest.read_text(encoding="utf-8"))["files"]
        if recorded != dict(pinned):
            bad.append("MISMATCH MANIFEST.json does not record the pinned set")
    for line in bad:
        print(line)
    if bad:
        print(f"\nFAIL: {len(bad)} problem(s). Run without --check to re-fetch.")
        return 1
    print(f"OK — Swagger UI {VERSION}, {len(pinned)} files, every hash matches.")
    return 0


def fetch(version: str) -> int:
    print(f"swagger-ui-dist {version} — asking the registry what the tarball "
          f"should hash to")
    with urllib.request.urlopen(f"{REGISTRY}/{version}", timeout=60) as r:
        meta = json.load(r)
    tarball = meta["dist"]["tarball"]
    integrity = meta["dist"].get("integrity", "")

    print(f"  {tarball}")
    with urllib.request.urlopen(tarball, timeout=300) as r:
        blob = r.read()
    print(f"  {len(blob):,} bytes")

    # The registry's own statement about its own artifact, checked before the
    # archive is opened -- a tarfile is parsed code, and verifying after
    # extracting verifies nothing.
    if integrity.startswith("sha512-"):
        want = integrity.split("-", 1)[1]
        got = base64.b64encode(hashlib.sha512(blob).digest()).decode()
        if got != want:
            print(f"FAIL: tarball integrity mismatch\n  want {want}\n  got  {got}")
            return 1
        print("  integrity OK (sha512 matches dist.integrity)")
    else:
        print(f"FAIL: registry published no sha512 integrity for {version}")
        return 1

    extracted = {}
    licences = {}
    with tarfile.open(fileobj=io.BytesIO(blob), mode="r:gz") as tf:
        for name in PINNED:
            member = tf.extractfile(f"package/{name}")
            if member is None:
                print(f"FAIL: {name} is not in the tarball")
                return 1
            extracted[name] = member.read()
        for name, dest_name in LICENCE_FILES.items():
            member = tf.extractfile(f"package/{name}")
            if member is None:
                print(f"FAIL: {name} is not in the tarball")
                return 1
            licences[dest_name] = member.read()

    problems = []
    for name, data in extracted.items():
        got = sha256(data)
        want = PINNED.get(name)
        if want and got != want:
            problems.append(f"  {name}\n    want {want}\n    got  {got}")
    if problems:
        print("FAIL: extracted files do not match the pinned hashes.")
        print("\n".join(problems))
        print("\nIf this is an intended version bump, update PINNED and say so in "
              "the commit.\nIf it is not, something replaced bytes the registry "
              "already vouched for.")
        return 1

    # Everything verified: only now does anything touch the working tree. The
    # directory is not rmtree'd the way the Pyodide fetcher does it, because
    # this one writes every file it is responsible for and an operator who
    # dropped something else in here is owed an error from
    # `check-licences.py` rule 1 rather than a silent deletion.
    DEST.mkdir(parents=True, exist_ok=True)
    for name, data in sorted(extracted.items()):
        (DEST / name).write_bytes(data)
        print(f"  wrote {name}  ({len(data):,} bytes)")
    for dest_name, data in sorted(licences.items()):
        (LICENSES / dest_name).write_bytes(data)
        print(f"  wrote licenses/{dest_name}  ({len(data):,} bytes)")

    # newline="\n" is load-bearing on Windows: `write_text` opens in text mode
    # and translates every \n to os.linesep, so the same script produced a
    # different MANIFEST.json on the two machines this repo is developed on.
    # This is the one file whose whole job is recording exact bytes.
    (DEST / "MANIFEST.json").open("w", encoding="utf-8", newline="\n").write(json.dumps({
        "package": "swagger-ui-dist",
        "version": version,
        "licence": "Apache-2.0",
        "source": "https://registry.npmjs.org/swagger-ui-dist",
        "tarball": tarball,
        "tarball_integrity": integrity,
        "files": {n: sha256(d) for n, d in sorted(extracted.items())},
        "note": ("The two files FastAPI's /docs HTML loads, and nothing else. "
                 "The published package unpacks to 11.7 MB; the ES bundles, "
                 "the standalone preset and the source maps are not served by "
                 "this app and are not shipped."),
    }, indent=2, sort_keys=True) + "\n")
    print("  wrote MANIFEST.json")
    print(f"\nOK — Swagger UI {version} vendored to static/lib/swagger-ui/")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="verify what is on disk; no network, no writes")
    ap.add_argument("--version", default=VERSION)
    args = ap.parse_args()
    if args.check:
        return check_on_disk()
    return fetch(args.version)


if __name__ == "__main__":
    sys.exit(main())
