#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Verify `LEDGER.md` against `.pantheon/ledger/claims.py`, and render it on request.

`P19-01`. The owner asked for an evidence trail proving Pantheon is a better
Odysseus. The first design question was not *what goes in it* but *what stops it
being false in a week*, because this file's whole value is that a stranger can
check it.

**A HAND-WRITTEN LEDGER IS THE SECOND PLACE EVERY FACT ALREADY LIVES.**

`.pantheon/ROADMAP.md` records what was done and what verifies it. `CHANGELOG.md`
records what changed, because AGPL-3.0 §5(a) requires it. A third file restating
those numbers in marketing voice is `Law 13` — and it is the copy shown to
strangers, so it is the worst one to let drift.

So the ledger is generated, and `--check` fails when the file in the tree is not
what this script produces. Editing `LEDGER.md` by hand breaks CI on the next run,
which is the only reliable way to stop somebody doing it.

**WHAT `--check` ACTUALLY VERIFIES**, beyond staleness — each of these is a way a
proof ledger goes quietly wrong:

  * a claim citing a file that no longer exists (the claim outlived its evidence)
  * a claim citing a roadmap row or decision that was never written
  * a provenance tag outside the five (an unranked claim reads as a ranked one)
  * an `after` with no `before` — an assertion wearing a measurement's clothes
  * the retrieval rows losing their `fixture` tag, which is the specific
    honesty this ledger would most like to lose
  * **the stated distance behind upstream having drifted**, checked against a
    live `git rev-list` on any checkout that has the `upstream` remote
  * **the README disagreeing with either of them.** The README is the front door
    and it restates two figures: the test count on its badge and the tracked/done
    line. Both had already rotted once — the badge read `6,301 passing` against a
    suite of 8,642, and the status line said 296 tracked / 77 done against a
    tracker saying 376 / 170. A stale number on the front page of a repository
    whose whole pitch is *our numbers are checkable* is the worst possible place
    for one, so they are pinned here rather than trusted to a future editor.

**VERIFYING IS THE DEFAULT AND WRITING TAKES A FLAG**, which is not a style
choice. `release-gate.py` discovers `.pantheon/check-*.py` and runs any checker
CI does not declare with **no arguments at all** — so a script in this directory
that writes when called bare would silently rewrite a tracked file in the middle
of a gate run, and the gate would pass because it did.

Usage:
    python3 .pantheon/check-ledger.py            # verify; writes nothing
    python3 .pantheon/check-ledger.py --write    # regenerate LEDGER.md
"""
from __future__ import annotations

import argparse
import functools
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / ".pantheon"))

from ledger import claims as C  # noqa: E402

OUTPUT = ROOT / "LEDGER.md"
TRACKER = ROOT / ".pantheon" / "ROADMAP.md"
README = ROOT / "README.md"
DECISIONS = ROOT / ".pantheon" / "DECISIONS.md"

# The retrieval numbers are the ones a reader is most likely to quote and the
# ones measured on a harness fixture. If either ever loses its tag, the ledger
# starts making a claim about the product that its own corpus refuses to support.
MUST_BE_FIXTURE = ("retrieval-recall", "retrieval-mrr")

BANNER = "<!-- GENERATED by .pantheon/check-ledger.py from .pantheon/ledger/claims.py. Do not edit. -->"


def _rows_index() -> set:
    """Every row id and decision id this repo has actually written.

    Read as text rather than parsed: a row id is a row id whether it sits in a
    heading, a `Depends:` clause or a sentence, and the only question here is
    whether the ledger is citing something that exists.
    """
    text = ""
    for path in (TRACKER, DECISIONS):
        if path.exists():
            text += path.read_text(encoding="utf-8")
    return set(text.split())


def _upstream_gap_problems() -> list:
    """Check the behind-by-N claim against a live `git rev-list`, where one is possible.

    `P19-05` asked for this number to be *measured, not typed*. It cannot always
    be: the `upstream` remote lives on the deployment box, and the cloud mirror's
    history begins at an import commit. So this verifies where it can and says
    plainly that it could not where it cannot — which is the honest shape for a
    check that depends on something not every checkout has.

    **Silence would be the defect here.** A rule that quietly passes when it
    cannot run is indistinguishable from a rule that ran and agreed, and this
    particular number is the one the ledger uses to admit a weakness. A stale
    *12 behind* that has drifted to 40 makes the limitations section read as
    thorough while being wrong.
    """
    by_id = {c.id: c for c in C.CLAIMS}
    claim = by_id.get("behind-upstream")
    if claim is None:
        return ["the behind-upstream claim is gone — the ledger no longer states the gap"]
    # `git cherry`, not `git rev-list`. **This distinction was found by this
    # check failing**, which is the only reason it is right now.
    #
    # `rev-list FORK..upstream` counts commits upstream has that are not
    # reachable from the fork point — and cherry-picking does not change that,
    # because a cherry-pick is a NEW commit with a new sha. After landing five
    # upstream fixes the naive count still said 12, so the ledger would have
    # been forced to keep claiming a gap it had just closed.
    #
    # `git cherry` compares **patch ids**, so a cherry-picked fix registers as
    # `-` (we have an equivalent) and only genuinely absent work counts as `+`.
    try:
        proc = subprocess.run(
            ["git", "cherry", "main", C.UPSTREAM_REF],
            cwd=str(ROOT), capture_output=True, text=True, timeout=60,
        )
    except (OSError, subprocess.SubprocessError):
        return []
    if proc.returncode != 0:
        # No upstream remote here. Not a failure — most checkouts are like this.
        return []
    live = str(sum(1 for line in proc.stdout.splitlines() if line.startswith("+")))
    stated = re.match(r"(\d+)", claim.after.strip())
    if stated is None:
        return ["behind-upstream: the `after` no longer starts with a count"]
    if stated.group(1) != live:
        return [
            f"behind-upstream says {stated.group(1)} and `git cherry main "
            f"{C.UPSTREAM_REF}` says {live} — upstream moved"
        ]
    return []


def _checker_count_problems() -> list:
    """The checker count, against the file the gate actually reads.

    `B59`. This claim said **fifteen** while `ci.yml` listed seventeen — it had
    drifted twice without anybody noticing, because the number lives in prose
    and nothing compared it to the list. That is the same shape as the README
    figures two functions down, and the same fix: the ledger's own arithmetic
    is the first thing a sceptic checks, so it is the last thing that should be
    typed from memory.

    Counted from `ci.yml` rather than from the gate, because the gate reads
    `ci.yml` too and a check that consults the same derived value twice proves
    only that the derivation is deterministic.
    """
    by_id = {c.id: c for c in C.CLAIMS}
    claim = by_id.get("checkers")
    if claim is None:
        return ["the checkers claim is gone — the ledger no longer states the count"]
    try:
        ci = (ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    except OSError:
        return []
    live = len(re.findall(r"^\s*- name: check-[\w-]+\s*$", ci, re.M))
    if not live:
        return []
    stated = re.match(r"(\d+)", claim.after.strip())
    if stated is None:
        return ["checkers: the `after` no longer starts with a count"]
    if int(stated.group(1)) != live:
        return [
            f"checkers says {stated.group(1)} and `ci.yml` lists {live} "
            f"`- name: check-*` steps"
        ]
    return []


# `B348`. Every claim carries a command you can run — that is this file's whole
# thesis — and for one of them the command **disproved the claim**: `wiring` said
# `after 2` while `check-wiring.py` printed `UNRESOLVED 120`, and its repro said
# `--max 124` against CI's `--max 120`. Nothing compared either.
#
# So: when a claim's repro is a `.pantheon/check-*.py` invocation, run it.
#
#   * **the headline.** Most checkers end their summary line with their own
#     verdict — `… · UNRESOLVED 120`, `… · FORKED 0`, `… · PROBLEMS 0`. When a
#     checker prints one AND the claim's `after` starts with a number, the two
#     must be the same number. That is exact, and it is the comparison that
#     catches a claim whose repro contradicts it.
#   * **the ceiling.** A `--max N` in a repro is an instruction to the reader
#     about which gate to run. If it is not the gate `ci.yml` runs, the reader
#     measures something CI does not guard.
#
# What is deliberately NOT a failure: a claim whose `after` is simply a
# different metric from the checker's headline — `fan-out`'s *40 destinations*
# against an unpaced-call-site count, for instance. Those are printed as NOTEs
# by `main()` and named in `B411`, because deciding what each of those numbers
# means needs the person who measured it, and a checker that guesses is the
# defect this one exists to find.
_REPRO_CHECKER = re.compile(r"python3?\s+(\.pantheon/check-[\w-]+\.py)")
_REPRO_CEILING = re.compile(r"--(max[\w-]*)\s+(\d+)")
_HEADLINE = re.compile(r"^([A-Z][A-Z -]*?)\s+(\d[\d,]*)$")
_LEADING_NUMBER = re.compile(r"(\d[\d,]*)")


@functools.lru_cache(maxsize=None)
def _checker_output(script: str) -> str:
    """The checker's own stdout, run with no arguments — so the number is the
    checker's verdict and not something a `--max` flag decided.

    Cached for the life of the process: six checkers take about twenty seconds
    between them, `verify()` is called once by the gate and forty times by
    `tests/test_a_claim_cannot_outlive_its_evidence.py`, and a checker's answer
    cannot change while nothing is editing the tree (`Law 19`).
    """
    proc = subprocess.run([sys.executable, str(ROOT / script)], cwd=str(ROOT),
                          capture_output=True, text=True, timeout=300)
    return proc.stdout


def _repro_headline(output: str):
    """`(name, value)` from a summary line's last `·` field, or None."""
    for line in output.splitlines():
        if not line.strip():
            continue
        fields = [f.strip() for f in line.split("·")]
        match = _HEADLINE.match(fields[-1])
        return (match.group(1), int(match.group(2).replace(",", ""))) if match else None
    return None


def _measured_anything(output: str) -> bool:
    """True when the checker printed a number other than zero."""
    return any(int(n.replace(",", "")) for n in re.findall(r"\d[\d,]*", output))


def _repro_problems() -> tuple:
    """`(problems, notes)` — see the comment above for which is which."""
    problems, notes = [], []
    try:
        ci = (ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    except OSError:
        ci = ""
    for claim in C.CLAIMS:
        match = _REPRO_CHECKER.search(claim.repro)
        if not match:
            continue
        script = match.group(1)
        if not (ROOT / script).exists():
            problems.append(f"{claim.id}: repro names {script}, which does not exist")
            continue
        try:
            output = _checker_output(script)
        except (OSError, subprocess.SubprocessError) as exc:
            problems.append(
                f"{claim.id}: repro names {script} and it could not be run ({exc}). "
                f"A claim whose command does not run is not reproducible.")
            continue

        stated = _LEADING_NUMBER.match(claim.after.strip())
        headline = _repro_headline(output)
        if headline and not _measured_anything(output):
            # Every number the checker printed is zero, which is what a checker
            # that enumerated nothing looks like — a checkout with no `.git`,
            # for one. A rule that reads that as "the claim is wrong" is the
            # tautology this whole file exists to refuse.
            notes.append(
                f"{claim.id}: {script} measured nothing here (every count zero), "
                f"so its output cannot confirm or deny `after {claim.after.strip()}`")
            headline = None
        if stated and headline:
            said = int(stated.group(1).replace(",", ""))
            if said != headline[1]:
                problems.append(
                    f"{claim.id}: says `after {claim.after.strip()}` and its own repro "
                    f"`{claim.repro}` prints {headline[0]} {headline[1]} — the command "
                    f"the claim names disproves the claim")
        elif stated:
            token = stated.group(1).replace(",", "")
            if not re.search(rf"(?<![\d,]){token}(?![\d,])", output):
                notes.append(
                    f"{claim.id}: `after {claim.after.strip()}` and {script} prints no "
                    f"such number (B411)")

        ceiling = _REPRO_CEILING.search(claim.repro)
        if ceiling and ci:
            in_ci = re.search(
                rf"{re.escape(script)}\s+--{ceiling.group(1)}\s+(\d+)", ci)
            if in_ci and in_ci.group(1) != ceiling.group(2):
                problems.append(
                    f"{claim.id}: repro runs {script} --{ceiling.group(1)} "
                    f"{ceiling.group(2)} and ci.yml runs --{ceiling.group(1)} "
                    f"{in_ci.group(1)} — a reader following the ledger runs a "
                    f"different gate from the one guarding the tree")
            elif not in_ci:
                notes.append(
                    f"{claim.id}: repro runs {script} --{ceiling.group(1)} "
                    f"{ceiling.group(2)} and ci.yml does not run it with that flag")
    return problems, notes


def _fork_date_problems() -> list:
    """`B349`. The §5(a) surface and the ledger must agree on the clone date.

    Two dates, two meanings: `FORK_POINT_DATE` is when `b4d1293` was committed
    upstream, `FORK_CLONE_DATE` is when this repository was taken from it. Only
    the second is the *Date of fork* in `NOTICE`, which is the attribution the
    licence requires — so that is the one pinned here. The first cannot be
    checked from a worktree at all: `b4d1293` is not reachable.
    """
    notice = ROOT / "NOTICE"
    if not notice.exists():
        return ["NOTICE is missing — the AGPL §5(a) modification notice is the file"]
    text = notice.read_text(encoding="utf-8")
    stated = re.search(r"Date of fork\s*:\s*(\d{4}-\d{2}-\d{2})", text)
    if stated is None:
        return ["NOTICE no longer carries a `Date of fork:` line"]
    clone = getattr(C, "FORK_CLONE_DATE", None)
    if clone is None:
        return ["claims.py no longer defines FORK_CLONE_DATE — see B349"]
    problems = []
    if clone == getattr(C, "FORK_POINT_DATE", object()):
        problems.append(
            "FORK_CLONE_DATE and FORK_POINT_DATE are the same date. They are two "
            "different events — the upstream commit, and the clone — and if they "
            "really coincide, say so where they are defined (B349).")
    if stated.group(1) != clone:
        problems.append(
            f"NOTICE says the fork is dated {stated.group(1)} and claims.py's "
            f"FORK_CLONE_DATE is {clone}. These are the same fact in two files and "
            f"one of them has moved (B349).")
    return problems


def _readme_problems() -> list:
    """The two figures the README restates, checked against their sources.

    The README cannot be generated — it is prose, and a templated front page
    reads like one. So the numbers in it are pinned instead: change the suite or
    the tracker without changing the README and this fails, which is the same
    bargain `check-tracker.py` already makes with the progress entries.
    """
    problems = []
    if not README.exists():
        return ["README.md is missing"]
    readme = README.read_text(encoding="utf-8")

    by_id = {c.id: c for c in C.CLAIMS}
    tests = by_id.get("tests")
    if tests is not None:
        # "920 test files · 8,642 passing" -> the passing count is what the badge shows.
        passing = tests.after.split("·")[-1].strip().split()[0]
        if f"tests-{passing.replace(',', '%2C')}%20passing" not in readme:
            problems.append(
                f"README badge does not read {passing} passing, which is what the "
                f"ledger's 'tests' claim says"
            )
        if f"**{passing} passing**" not in readme:
            problems.append(f"README status line does not state {passing} passing")

    if TRACKER.exists():
        for line in TRACKER.read_text(encoding="utf-8").splitlines():
            if line.startswith("| **Total**"):
                cells = [c.strip().strip("*") for c in line.split("|")]
                tracked, done = cells[3], cells[6]
                if f"**{tracked} tracked tasks, {done} done" not in readme:
                    problems.append(
                        f"README says something other than '{tracked} tracked tasks, "
                        f"{done} done' — the tracker's Total row moved"
                    )
                break
    return problems


def verify() -> list:
    """Every way a claim can be wrong that a script can see. Returns problems."""
    problems = []
    seen = set()
    areas = {name for name, _ in C.AREAS}
    corpus = _rows_index()

    for claim in C.CLAIMS:
        where = f"{claim.id}"
        if claim.id in seen:
            problems.append(f"{where}: two claims share this id")
        seen.add(claim.id)

        if claim.area not in areas:
            problems.append(f"{where}: area {claim.area!r} is not in AREAS")

        if claim.provenance not in C.PROVENANCE:
            problems.append(
                f"{where}: provenance {claim.provenance!r} is not one of {C.PROVENANCE}"
            )

        if not claim.repro.strip():
            problems.append(f"{where}: no reproduction command — 'trust us' is not evidence")

        # A lone `after` is the shape this rule exists to catch: a number with
        # nothing to compare it to reads as an improvement and is not one.
        has_before, has_after = bool(claim.before.strip()), bool(claim.after.strip())
        if has_after != has_before:
            problems.append(
                f"{where}: has {'after' if has_after else 'before'} but not the other — "
                f"a one-sided measurement is an assertion"
            )

        for path in claim.evidence:
            if not (ROOT / path).exists():
                problems.append(f"{where}: cites {path}, which does not exist")

        for row in claim.rows:
            # Row ids appear in prose wrapped in backticks, bold, or bare.
            if not any(row in token for token in corpus):
                problems.append(
                    f"{where}: cites {row}, which is in neither ROADMAP.md nor DECISIONS.md"
                )

        if not claim.how.strip():
            problems.append(f"{where}: no 'how' — the method is the part worth reading")

    by_id = {c.id: c for c in C.CLAIMS}
    for cid in MUST_BE_FIXTURE:
        claim = by_id.get(cid)
        if claim is None:
            problems.append(f"{cid}: expected to exist and carry the fixture tag; it is gone")
        elif claim.provenance != "fixture":
            problems.append(
                f"{cid}: provenance is {claim.provenance!r} and must be 'fixture' — "
                f"the corpus declares itself a harness and the ledger must say so"
            )

    problems.extend(_readme_problems())
    problems.extend(_upstream_gap_problems())
    problems.extend(_checker_count_problems())
    problems.extend(_repro_problems()[0])
    problems.extend(_fork_date_problems())

    if not any(c.provenance == "diffed" for c in C.CLAIMS):
        problems.append(
            "no claim is tagged 'diffed' — without one, nothing here is measured "
            "against upstream's actual tree"
        )
    return problems


def _table(rows) -> str:
    out = ["| Measure | Odysseus | Pantheon | Provenance |", "| --- | --- | --- | --- |"]
    for c in rows:
        if not c.before.strip():
            continue
        out.append(f"| {c.headline} | `{c.before}` | **`{c.after}`** | `{c.provenance}` |")
    return "\n".join(out)


def render() -> str:
    p = []
    a = p.append
    a(BANNER)
    a("")
    a("# Pantheon — the proof ledger")
    a("")
    a(f"> A fork of **Odysseus** (`{C.UPSTREAM_REMOTE}`, AGPL-3.0-or-later).")
    a(f"> Fork point `{C.FORK_POINT}`, {C.FORK_POINT_DATE} — *{C.FORK_POINT_SUBJECT}*.")
    a(f"> Every figure below measured {C.MEASURED_ON}.")
    a("")
    a("**This file is generated.** It is rendered from `.pantheon/ledger/claims.py` by")
    a("`.pantheon/check-ledger.py`, and CI fails if the two disagree. Edit the claims,")
    a("not this file.")
    a("")
    a("## How to read a row")
    a("")
    a("A ledger is worth exactly what its weakest number is worth. One figure that does")
    a("not survive being checked is not one bad row — it is the row a sceptic quotes, and")
    a("everything above and below it then reads as the same kind of thing. So every claim")
    a("here names **where its number came from** and **a command you can run**. Some of")
    a("these numbers are weaker than others; the tag says which.")
    a("")
    for tag in C.PROVENANCE:
        a(f"- **`{tag}`** — {C.PROVENANCE_MEANS[tag]}")
    a("")
    a("If you only check one thing, check a `fixture` row against its own corpus. Those")
    a("are the numbers most likely to be quoted and least able to carry the weight.")
    a("")
    a("## At a glance")
    a("")
    a(_table(C.CLAIMS))
    a("")
    a("---")
    a("")

    for name, blurb in C.AREAS:
        rows = [c for c in C.CLAIMS if c.area == name]
        if not rows:
            continue
        a(f"## {name}")
        a("")
        a(f"*{blurb}*")
        a("")
        for c in rows:
            a(f"### {c.headline}")
            a("")
            if c.before.strip():
                a(f"**`{c.before}` → `{c.after}`**  ·  provenance **`{c.provenance}`**")
            else:
                a(f"provenance **`{c.provenance}`**")
            a("")
            a(f"**Odysseus:** {c.stock}")
            a("")
            a(f"**Pantheon:** {c.pantheon}")
            a("")
            a(f"**How we got there.** {c.how}")
            a("")
            a("```")
            a(c.repro)
            a("```")
            if c.rows:
                a("")
                a("Argued in: " + ", ".join(f"`{r}`" for r in c.rows) + ".")
            a("")
        a("---")
        a("")

    a("## What this ledger does not prove")
    a("")
    a("Stated here rather than left for a reader to find, because a ledger with no")
    a("limitations section reads as marketing.")
    a("")
    a("1. **The retrieval numbers are measured on a harness fixture.** They prove the")
    a("   scorer works and that two engines were compared over one corpus. They are not")
    a("   a measurement of how well Pantheon remembers in daily use, and no number in")
    a("   this repository is. Building one takes an operator's own memories and probes")
    a("   they wrote themselves: `.pantheon/retrieval_eval.py --generate`.")
    a("2. **Seven upstream commits are unmerged** — documentation restructuring and")
    a("   dependency bumps, deliberately declined. The five real fixes were")
    a("   cherry-picked on 2026-09-12 (`P19-06`) and the two that were a security")
    a("   advisory were backported ahead of them (`B70`). Measuring this gap is what")
    a("   found them: a bearer API token had inherited its minting admin's tool")
    a("   authority, and an approval grant was readable out of caller-writable message")
    a("   metadata. **A fork that stops taking upstream's fixes does not merely go")
    a("   stale.**")
    a("3. **Most rows compare code, not outcomes.** *Fewer unreachable handlers* and")
    a("   *every silent failure explained* are real and checkable; neither is a")
    a("   measurement of a person getting their work done faster.")
    a("4. **Most rows here are about this fork's own tree.** The suite is green —")
    a("   8,819 passing, nothing red, after 14 standing failures were cleared on")
    a("   2026-09-12 — but a green suite is evidence about the code under it, not")
    a("   about a deployment. `P10-10`'s manual pass over every surface is still")
    a("   not done, and no automated check substitutes for it.")
    a("")
    a("## Reproducing all of it")
    a("")
    a("```")
    a("python3 .pantheon/release-gate.py        # all 15 checkers plus the suite")
    a("python3 .pantheon/retrieval_eval.py      # the memory numbers, with their caveat")
    a("python3 .pantheon/check-ledger.py          # this file, verified")
    a("```")
    a("")
    a("The `diffed` rows need the upstream remote:")
    a("")
    a("```")
    a(f"git remote add upstream https://github.com/{C.UPSTREAM_REMOTE}.git")
    a("git fetch upstream")
    a(f"git diff --shortstat {C.FORK_POINT}..HEAD")
    a("```")
    a("")
    return "\n".join(p) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true",
                    help="regenerate LEDGER.md (default is to verify and write nothing)")
    args = ap.parse_args()

    problems = verify()
    rendered = render()
    # `B348`. Printed whether the run passes or fails: a claim whose stated
    # number its own repro never prints is not provably wrong — it may be a
    # different metric — but it is not checkable either, and silence about that
    # is how `wiring` sat at `2` against a checker printing `120`.
    notes = _repro_problems()[1]

    if not args.write:
        if not OUTPUT.exists():
            problems.append("LEDGER.md does not exist — run with --write to create it")
        elif OUTPUT.read_text(encoding="utf-8") != rendered:
            problems.append(
                "LEDGER.md is stale or was hand-edited — run "
                "`python3 .pantheon/check-ledger.py --write` and commit the result"
            )
        if problems:
            print(f"ledger FAILED — {len(problems)} problem(s)\n")
            for p in problems:
                print(f"  {p}")
            return 1
        fixture = sum(1 for c in C.CLAIMS if c.provenance == "fixture")
        print(
            f"ledger OK — {len(C.CLAIMS)} claims across {len(C.AREAS)} areas, "
            f"{fixture} labelled fixture, every cited path present"
        )
        for note in notes:
            print(f"  NOTE  {note}")
        return 0

    if problems:
        print(f"ledger FAILED — {len(problems)} problem(s), nothing written\n")
        for p in problems:
            print(f"  {p}")
        return 1
    for note in notes:
        print(f"  NOTE  {note}")
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} — {len(C.CLAIMS)} claims")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
